### ISSUE TITLE
url_for helper to build URLs

### ISSUE THREAD

**Issue by indatwood** [pyrates/roll#119]
Hi, I was missing a simple helper to create URLs for me (and ensure these URLs are working correclty), so I crafted something for my own usage.

It might be helpful to others, so here is a link for it. It's very fresh so any feedback is appreciated, maybe there are better ways to iterate on the routes, or to do this.

Here is a link : https://github.com/indatwood/copanier/blob/wip/copanier/views/core.py#L93-L115

**Comment by yohanboniface** [comment]
hi @indatwood and thanks for the suggestion.

This is something we'd like to implement, not totally sure though if this should land in roll itself or in autoroutes.

Anyway, I'd use a slightly different pattern:
- at route creation time, index the name/url pairs, so we don't need to compute it at runtime
- clean any variable identifier (eg. remove `path` in `/foo/bar/{var:path}`), otherwise python will complain when doing the string formatting
- maybe use the module name in the route name, to namespace routes and avoid collisions, eg. `my_app.home`, `myother_app.home`
- if the `route` call receive a `name` parameter (optional), use it instead

**Comment by indatwood** [comment]
Hey, thanks for the answer. I've done it this way because I didn't want to patch autoroutes directly, but what you're proposing makes sense :-)
